"""Initial migration

Revision ID: 30cecacf6d0c
Revises:
Create Date: 2023-04-08 23:28:43.200307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cecacf6d0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'users',
        Column('id', Integer, primary_key=True),
        Column('email', String(255), nullable=False),
        Column('password_hash', String(255), nullable=False),
        Column('name', String(255), nullable=False),
        Column('age', Integer, nullable=False),
        Column('weight', Float, nullable=False),
        Column('height', Float, nullable=False)
    )

    conn = op.get_bind()
    conn.execute(
        text(
            """
            INSERT INTO users (email, password_hash, name, age, weight, height)
            VALUES
                ('test@test.com', 'password', 'Test User', 30, 80.0, 180.0),
                ('example@example.com', 'password', 'Example User', 25, 70.0, 175.0)
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
